name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      id: checkout-repo
      uses: actions/checkout@v3

    - name: AWS credentials
      id: aws-credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ECR_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.ECR_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Extract repository name
      id: get-repository-name
      shell: bash
      run: echo "##[set-output name=repository;]$(echo ${GITHUB_REPOSITORY#/})"

    - name: Extract branch name
      id: get-branch-name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

    - name: Build the Docker image
      id: build-and-push-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ steps.get-repository-name.outputs.repository }}
        IMAGE_TAG: prod-1.0.${{ github.run_number }}
      run: |
        docker build --file Dockerfile $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
